# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "AlbanMontaigu/boot2docker"
  config.vm.define "dev-env"
  config.vm.hostname = 'dev-env'
  config.vm.provider :virtualbox do |vb|
	vb.name = "dev-env"
  end
  # login with docker/tcuser
  for i in 8080..8090
    config.vm.network :forwarded_port, guest: i, host: i
  end
    config.vm.network :forwarded_port, guest: 8761, host: 8761
  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.synced_folder "../../../Git", "/home/docker/git"
  config.vm.synced_folder "#{Dir.home}/.m2", "/home/docker/.m2"
  config.vm.synced_folder "./", "/home/docker/"
  config.ssh.username = "docker"
  config.ssh.password = "tcuser"
#  config.vm.provision "shell", path: "install.sh"
  config.vm.provision "shell", inline: <<-SHELL
    export PATH="$PATH:/home/docker/scripts"
  SHELL
end
