# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "AlbanMontaigu/boot2docker"
  config.vm.define "dev-env"
  config.vm.hostname = 'dev-env'
  config.vm.provider :virtualbox do |vb|
	vb.name = "dev-env"
  end
  # login with docker/tcuser
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.synced_folder "../../../Git", "/git"
#  config.vm.provision "shell", inline: <<-SHELL
#    source /vagrant/vagrant/install.sh; provision
#  SHELL
end
